### Basic Mathematics

In [7]:
import numpy as np

x = np.random.random()
print("Random number: ", x)
x_square_root =  np.sqrt(x)
print("Number square root: ", x_square_root)
print("x^sqrt(x): ", np.power(x, x_square_root))
matrix = np.random.random(3)
print("Random matrix: ", matrix)
matrix = np.append(matrix, np.random.random(2))
print("New matrix", matrix)
print("Sine of matrix", np.sin(matrix))

Random number:  0.1980497185301956
Number square root:  0.44502777276277444
x^sqrt(x):  0.48645760983858305
Random matrix:  [0.28184488 0.61596481 0.24634105]
New matrix [0.28184488 0.61596481 0.24634105 0.32595592 0.38309051]
Sine of matrix [0.27812821 0.57774629 0.24385711 0.32021452 0.37378874]


### Tour of Numpy

In [5]:
import numpy as np

mvalues = [0,1,5,6,80]
# print(mvalues)
M = np.array(mvalues)
# print(M)
x = np.arange(20, 104.75, 3.6 )
# print("x np.arange = ", x)
y = np.linspace(20, 104.75, 10)
# print("y np.inespace = ", y)

_,spacing = np.linspace(20, 104.75, 10, retstep=True) # _ beacuse we dont care about the actual array now
x = np.array([1,2,3,4])
type(x)
np.ndim(x)

1

In [6]:
x = np.array(
    [
        [[1,2], [3,4]],
        [[5,6], [7,8]],
        [[9,10], [11,12]]
    ]
)

x

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [7]:
x.ndim

3

In [8]:
np.shape(x)

(3, 2, 2)

In [10]:
X =  np.arange(24).reshape(4,6)
X

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
X.shape

(4, 6)

In [22]:
X[0:4,1:4]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [25]:
z = np.zeros((3,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
I = np.identity((4))
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.eye(5,8,k=1, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

### Matrices

In [46]:
import numpy as np

a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2),7, np.int)
d = np.eye(2)
e = np.random.random((2,2))
f = np.array([[1,2,3,4], [11,22,33,44], [111,222,333,444]])
f

array([[  1,   2,   3,   4],
       [ 11,  22,  33,  44],
       [111, 222, 333, 444]])

### Deviations

In [51]:
import numpy as np 

A = np.array([[1,2],[3,4],[9,10]])
A.std(axis=0) # 0 - row, 1 - columns

array([3.39934634, 3.39934634])

In [52]:
np.std(A)

3.435921354681384

### Eigen Values

In [54]:
from numpy import linalg
import numpy as np

A = np.diag((1,2,7))
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 7]])

In [56]:
eigenvalues, _ = linalg.eig(A)
eigenvalues

array([1., 2., 7.])

In [57]:
B = np.array([[1,-1],[1,1]])
B

array([[ 1, -1],
       [ 1,  1]])

In [58]:
linalg.eig(B)

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [59]:
c = np.array([[1, -4, -2], [2, 1, 2], [3, 2, -1]])

In [60]:
c

array([[ 1, -4, -2],
       [ 2,  1,  2],
       [ 3,  2, -1]])

In [63]:
e, _ = linalg.eig(c)
e

array([ 1.66419427+3.7390158j,  1.66419427-3.7390158j,
       -2.32838855+0.j       ])

### Covariance

In [67]:
import numpy as np 
A = np.array([[1,2],[3,4]])
np.cov(A)

array([[0.5, 0.5],
       [0.5, 0.5]])